
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module ImageRecog(

    //////////// CLOCK //////////
    input                           ref_clk,

    //////////// SDRAM //////////    
    output            [12:0]        DRAM_ADDR,
    output             [1:0]        DRAM_BA,
    output                          DRAM_CAS_N,
    output                          DRAM_CKE,
    output                          DRAM_CLK,
    output                          DRAM_CS_N,
    inout             [15:0]        DRAM_DQ,
    output                          DRAM_LDQM,
    output                          DRAM_RAS_N,
    output                          DRAM_UDQM,
    output                          DRAM_WE_N,

    //////////// RST_n ////////
    input                           RST_n,
    //////////// KEY //////////
    input              [3:0]        KEY,

    //////////// LED //////////
    output             [9:0]        LEDR,

    //////////// SW //////////
    input              [9:0]        SW,

    //////////// VGA //////////
    output                          VGA_BLANK_N,
    output             [7:0]        VGA_B,
    output                          VGA_CLK,
    output             [7:0]        VGA_G,
    output                          VGA_HS,
    output             [7:0]        VGA_R,
    output                          VGA_SYNC_N,
    output                          VGA_VS,

    //////////// GPIO_1, GPIO_1 connect to D5M - 5M Pixel Camera //////////
    input             [11:0]        D5M_D,
    input                           D5M_FVAL,
    input                           D5M_LVAL,
    input                           D5M_PIXCLK,
    output                          D5M_RESET_N,
    output                          D5M_SCLK,
    inout                           D5M_SDATA,
    input                           D5M_STROBE,
    output                          D5M_TRIGGER,
    output                          D5M_XCLKIN
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================



endmodule
